apiVersion: vm.cluster.gke.io/v1
kind: VirtualMachineDisk
metadata:
  name: disk-from-registry2
spec:
  source:
    registry:
      url: "docker://kubevirt/fedora-cloud-container-disk-demo"
  size: 8Gi
  storageClassName: local-shared
---
apiVersion: vm.cluster.gke.io/v1
kind: VirtualMachine
metadata:
  name: my-kube-vm2
  namespace: default
  labels:
    special: key-kubevm
spec:
  osType: Linux
  interfaces:
  - name: eth4
    networkName: pod-network
  compute:
    cpu:
      vcpus: 1
    memory:
      capacity: 4G
  disks:
  - virtualMachineDiskName: disk-from-registry2
    boot: true
