apiVersion: constraints.gatekeeper.sh/v1beta1
kind: K8svmmemlimits
metadata:
  name: individual-vm-limit
spec:
  match:
    kinds:
      - apiGroups: ["vm.cluster.gke.io"]
        kinds: ["VirtualMachine"]
  parameters:
    cpu: 1
    memory: 6Gi
